// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rectangle.proto

package me.grpc.test.route;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.Point location = 2;</code>
   */
  me.grpc.test.route.Point getLocation();
  /**
   * <code>.Point location = 2;</code>
   */
  me.grpc.test.route.PointOrBuilder getLocationOrBuilder();
}
