// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rectangle.proto

package me.grpc.test.route;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  java.util.List<me.grpc.test.route.Feature> 
      getFeatureList();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  me.grpc.test.route.Feature getFeature(int index);
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  java.util.List<? extends me.grpc.test.route.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .Feature feature = 1;</code>
   */
  me.grpc.test.route.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
