// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rectangle.proto

package me.grpc.test.route;

public interface RouteSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 point_count = 1;</code>
   */
  int getPointCount();

  /**
   * <code>int32 feture_count = 2;</code>
   */
  int getFetureCount();

  /**
   * <code>int32 distance = 3;</code>
   */
  int getDistance();

  /**
   * <code>int32 elapsed_time = 4;</code>
   */
  int getElapsedTime();
}
