// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rectangle.proto

package me.grpc.test.route;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <code>.Point location = 1;</code>
   */
  me.grpc.test.route.Point getLocation();
  /**
   * <code>.Point location = 1;</code>
   */
  me.grpc.test.route.PointOrBuilder getLocationOrBuilder();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
